### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Asatsa** [Asatsa/internship_repo1#2]
# General Vision

**Become a proficient, competent bioinformatician**
**Actively support genomic research in the environmental and agricultural fields while mentoring young environmental scientists to make use of the limitless potential of Bioinformatics**

## Internship vision
By the end of this internship, I would like to have an understanding of the Bioinformatics area of research. I see myself having basic bioinformatic skills that would allow me pursue whatever  line of bioinformatics I choose.

This internship if my introduction into Bioinformatics.I will be allowed to explore the different tools and fields of Bioinformatics like a guided tour.
It consists of one month of close training and then a mini-project where I will get to work with my colleagues. I hope to contribute to the work at ICIPE.

## Milestones

- [x] Month one of training

- [x] Be proficient with GitHub

- [x] Introduction to genomics

- [ ] Learn python, Linux, bash

- [x] Learn data management

- [x] Introduction to principles of bioinformatics

- [ ] Complete a collaborative mini-project
